name: "End-to-end tests"

on: push

defaults:
  run:
    shell: bash

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Bootstrap
        run: . ./bootstrap.sh

      - name: Apply
        run: gulp

      - name: Re-apply
        run: gulp
