name: "Lint / unit test"

on: push

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test -- --ci
