name: "Unit & end-to-end tests"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test -- --ci --verbose

  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run bootstrapper
        run: . ./bootstrap.sh

      - name: Run installer
        run: gulp
